textos = {
    "labelInicioSesion":"Log in",
    "labelNickname":"Nickname",
    "labelContrasenia":"Password",
    "labelErrorInicio":"Error. Invalid nickname or passowrd",
    "btnRegistrarse":"Sign up",
    "btnIniciarSesion":"Log in",
    "labelRegistro":"Sign up",
    "labelRepetirContra":"Repeat password",
    "labelRol":"Rol",
    "rdbtnUser":"User",
    "rdbtnCreator":"Creator",
    "btnCancelar":"Cancel",
    "menuUsuario":"User",
    "actionPerfil":"Profile",
    "actionRecargar":"Recharge balance",
    "actionBiblio":"Library",
    "actionCerrarSesion":"Log out",
    "menuCatalogo":"Catalog",
    "actionAnadir":"Add game",
    "actionComprar":"Buy game",
    "menuConfig":"Settings",
    "labelPerfilUsuario":"User profile",
    "labelNickPerfil":"Nickname: ",
    "labelRolPerfil":"Profile type: ",
    "labelSaldoPerfil":"Remaining balance: ",
    "labelVentasPerfil":"Sales made: ",
    "labelIngreso":"Recharge account balance",
    "btnAñadirSaldo":"Add balance",
    "labelTituloBiblioteca":"User library",
    "cabecerasBiblioteca":["Name","Author","Genres","Play","Refund"],
    "btnJugar":"Play",
    "btnReembolsar":"Refund",
    "actionAnadirComentario":"Add a comment",
    "labelDecComantario":"Comment statement",
    "labelSeleccion":"Select a game",
    "labelPuntuacion":"Indicate the score",
    "labelInsertComent":"Insert comment",
    "plhdrComentario":"Max 250",
    "btnSubirComent":"Upload comment",
    "labelAñadirJuego":"Add a new game",
    "labelNombreJuego":"Game name",
    "labelGenerosJuego":"Game genres",
    "labelPrecioJuego":"Game price",
    "btnSubirJuego":"Upload game to the platform",
    "labelCatalogo":"Virtual catalog",
    "btnComprar":"Buy",
    "btnComentarios":"See comments",
    "cabecerasCatalogo":["Name","Author","Genres","Price","Buy","Comments"],
    "labelComentarios":"Comments",
    "textoComNickname":"Nickname: ",
    "textoComPuntuacion":"/10",
    "textoComComentario":"Comment: ",
    "labelTema":"Theme",
    "labelTamanio":"Font size",
    "labelIdioma":"Languaje",
    "rdbtnTemaDefect":"Default",
    "rdbtnTemaOscuro":"Dark",
    "rdbtnEsp":"Spanish",
    "rdbtnIng":"English",
    "btnReset":"Reset",
    "btnGuardar":"Save",
    "textografo":"Sales made",
    "textoErrorRegistro":"Error. Passwords must match.",
    "textoErrorIngresoSaldo":"Error. You cannot enter a negative amount",
    "textoPrevReembolso":"Are you sure you want a refund?",
    "textoErrorSaldoCompra":"Error. Insufficient balance",
    "textoErrorCompra":"Error. You already have this game in your library",
    "menuInformes":"Informs",
    "textoExitoCompra":"You have bought ",
    "tituloExito":"Success",
    "tituloError":"Error",
    "leyendaX":"Games",
    "leyendaY":"Total acquisitions",
    "labelTituloInformes":"Best-selling games so far",
    "textoExitoRecarga":"The balance has been correctly added to the account.",
    "textoErrorInput":"Error. Input not supported",
    "btnAceptar":"Accept",
    "tituloCancel":"Canceled",
    "textoExitoReembolso":"Has been successfully refunded",
    "textoCancelAccion":"The action has been cancelled",
    "textoExitoRegistro":"The account has been successfully registered",
    "textoExitoComent":"The comment has been uploaded successfully",
    "textoErrorComent":"You must leave at least a comment",
    "textoExitoSubida":"The game has been uploaded successfully",
    "textoErrorSubida":"Error. A game with this name already exists on the platform.",
    "tituloVentanaInicio":"Log in",
    "tituloVentanaRegistro":"User registration",
    "tituloVentanaPrincipal":"ExpectShop",
    "tituloVentanaComentarios":"Comments from ",
    "tituloVentanaReembolso":"Before anything"
}